BEGIN TRANSACTION;
CREATE TABLE "accounts_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "role" varchar(10) NOT NULL, "tuteur_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "accounts_profile" VALUES(1,'tuteur',NULL,1);
INSERT INTO "accounts_profile" VALUES(2,'etudiant',1,2);
INSERT INTO "accounts_profile" VALUES(3,'etudiant',1,3);
INSERT INTO "accounts_profile" VALUES(4,'etudiant',1,4);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,7,'add_profile','Can add profile');
INSERT INTO "auth_permission" VALUES(26,7,'change_profile','Can change profile');
INSERT INTO "auth_permission" VALUES(27,7,'delete_profile','Can delete profile');
INSERT INTO "auth_permission" VALUES(28,7,'view_profile','Can view profile');
INSERT INTO "auth_permission" VALUES(29,8,'add_cataloguemodule','Can add Module du catalogue');
INSERT INTO "auth_permission" VALUES(30,8,'change_cataloguemodule','Can change Module du catalogue');
INSERT INTO "auth_permission" VALUES(31,8,'delete_cataloguemodule','Can delete Module du catalogue');
INSERT INTO "auth_permission" VALUES(32,8,'view_cataloguemodule','Can view Module du catalogue');
INSERT INTO "auth_permission" VALUES(33,9,'add_categorieevaluation','Can add Catégorie d''évaluation');
INSERT INTO "auth_permission" VALUES(34,9,'change_categorieevaluation','Can change Catégorie d''évaluation');
INSERT INTO "auth_permission" VALUES(35,9,'delete_categorieevaluation','Can delete Catégorie d''évaluation');
INSERT INTO "auth_permission" VALUES(36,9,'view_categorieevaluation','Can view Catégorie d''évaluation');
INSERT INTO "auth_permission" VALUES(37,10,'add_inscription','Can add Inscription');
INSERT INTO "auth_permission" VALUES(38,10,'change_inscription','Can change Inscription');
INSERT INTO "auth_permission" VALUES(39,10,'delete_inscription','Can delete Inscription');
INSERT INTO "auth_permission" VALUES(40,10,'view_inscription','Can view Inscription');
INSERT INTO "auth_permission" VALUES(41,11,'add_modulechoisi','Can add Module choisi');
INSERT INTO "auth_permission" VALUES(42,11,'change_modulechoisi','Can change Module choisi');
INSERT INTO "auth_permission" VALUES(43,11,'delete_modulechoisi','Can delete Module choisi');
INSERT INTO "auth_permission" VALUES(44,11,'view_modulechoisi','Can view Module choisi');
INSERT INTO "auth_permission" VALUES(45,12,'add_note','Can add Note');
INSERT INTO "auth_permission" VALUES(46,12,'change_note','Can change Note');
INSERT INTO "auth_permission" VALUES(47,12,'delete_note','Can delete Note');
INSERT INTO "auth_permission" VALUES(48,12,'view_note','Can view Note');
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO "auth_user" VALUES(1,'pbkdf2_sha256$1200000$agzXQsfBhMcdwyCGRRIVBt$dCJNKHeOCjXJ40WXkAVwyunNmSJ138BqLSgrgXOeFbA=',NULL,0,'tuteur1','Ben Salem','tuteur@esp.tn',0,1,'2026-05-21 11:24:00.435464','Ahmed');
INSERT INTO "auth_user" VALUES(2,'pbkdf2_sha256$1200000$P8i017ng4bZnBa64ME3UIH$goFaFuKFDVRgYh+nfu1n/o+fr3tjmQlgqJsm/NZY/14=',NULL,0,'ali_ben_ali','Ben Ali','ali@esp.tn',0,1,'2026-05-21 11:24:00.824297','Ali');
INSERT INTO "auth_user" VALUES(3,'pbkdf2_sha256$1200000$jaU4YFGrMKEybmaZ3Hvr4j$U9O0pUiYUSL5oDDBoZ/lkuq/YKrnf6TG6pUeh1hi0gY=',NULL,0,'sarra_mrad','Mrad','sarra@esp.tn',0,1,'2026-05-21 11:24:01.391231','Sarra');
INSERT INTO "auth_user" VALUES(4,'pbkdf2_sha256$1200000$PlfxhcNahKM4cC6T36fXP6$2fvJ1FXk1DIXPUGi884OHBe2fKvpMdkhWaUsE2o0bZc=',NULL,0,'omar_triki','Triki','omar@esp.tn',0,1,'2026-05-21 11:24:01.715049','Omar');
INSERT INTO "auth_user" VALUES(5,'pbkdf2_sha256$1200000$EmCqKDAxcvk0QtI5MNaLOu$hmmPJ1PJTvLBAI5rIPfDAC0qcPYWJMaNfj9PumjIZHI=',NULL,1,'admin','','admin@esp.tn',1,1,'2026-05-21 11:24:02.307571','');
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "catalogue_cataloguemodule" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "intitule" varchar(200) NOT NULL UNIQUE, "coefficient" integer unsigned NOT NULL CHECK ("coefficient" >= 0), "description" text NULL, "est_actif" bool NOT NULL);
INSERT INTO "catalogue_cataloguemodule" VALUES(1,'Algorithmique et Structures de Données',10,'Bases de l''algorithmique, complexité, listes, arbres, graphes.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(2,'Programmation Orientée Objet',8,'Concepts de la POO : classes, héritage, polymorphisme, encapsulation.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(3,'Base de Données Relationnelles',8,'Modélisation, SQL, normalisation, transactions et optimisation.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(4,'Réseaux et Protocoles',6,'Modèle OSI/TCP-IP, protocoles, sécurité des réseaux.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(5,'Systèmes d''Exploitation',6,'Gestion des processus, mémoire, fichiers, Linux.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(6,'Développement Web Front-End',8,'HTML5, CSS3, JavaScript ES6+, frameworks modernes.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(7,'Développement Web Back-End',8,'Django, REST API, authentification, déploiement.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(8,'Intelligence Artificielle',6,'Machine learning, réseaux de neurones, traitement du langage.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(9,'Mathématiques Discrètes',4,'Logique, ensembles, combinatoire, théorie des graphes.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(10,'Génie Logiciel',6,'UML, méthodes agiles, tests, CI/CD, qualité du code.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(11,'Sécurité Informatique',4,'Cryptographie, OWASP, pentesting, cybersécurité.',1);
INSERT INTO "catalogue_cataloguemodule" VALUES(12,'Cloud et DevOps',4,'Docker, Kubernetes, AWS/Azure, pipelines CI/CD.',1);
CREATE TABLE "catalogue_categorieevaluation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nom" varchar(100) NOT NULL, "poids" decimal NOT NULL, "module_id" bigint NOT NULL REFERENCES "catalogue_cataloguemodule" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "catalogue_categorieevaluation" VALUES(1,'Contrôle Continu',30,1);
INSERT INTO "catalogue_categorieevaluation" VALUES(2,'Examen Terminal',50,1);
INSERT INTO "catalogue_categorieevaluation" VALUES(3,'TP',20,1);
INSERT INTO "catalogue_categorieevaluation" VALUES(4,'Contrôle Continu',40,2);
INSERT INTO "catalogue_categorieevaluation" VALUES(5,'Examen Terminal',60,2);
INSERT INTO "catalogue_categorieevaluation" VALUES(6,'Contrôle Continu',30,3);
INSERT INTO "catalogue_categorieevaluation" VALUES(7,'Projet',30,3);
INSERT INTO "catalogue_categorieevaluation" VALUES(8,'Examen Terminal',40,3);
INSERT INTO "catalogue_categorieevaluation" VALUES(9,'Contrôle Continu',40,4);
INSERT INTO "catalogue_categorieevaluation" VALUES(10,'Examen Terminal',60,4);
INSERT INTO "catalogue_categorieevaluation" VALUES(11,'TP',40,5);
INSERT INTO "catalogue_categorieevaluation" VALUES(12,'Examen Terminal',60,5);
INSERT INTO "catalogue_categorieevaluation" VALUES(13,'Projet',60,6);
INSERT INTO "catalogue_categorieevaluation" VALUES(14,'Contrôle Continu',40,6);
INSERT INTO "catalogue_categorieevaluation" VALUES(15,'Projet',70,7);
INSERT INTO "catalogue_categorieevaluation" VALUES(16,'Contrôle Continu',30,7);
INSERT INTO "catalogue_categorieevaluation" VALUES(17,'Projet',50,8);
INSERT INTO "catalogue_categorieevaluation" VALUES(18,'Examen Terminal',50,8);
INSERT INTO "catalogue_categorieevaluation" VALUES(19,'Contrôle Continu',50,9);
INSERT INTO "catalogue_categorieevaluation" VALUES(20,'Examen Terminal',50,9);
INSERT INTO "catalogue_categorieevaluation" VALUES(21,'Projet',60,10);
INSERT INTO "catalogue_categorieevaluation" VALUES(22,'Contrôle Continu',40,10);
INSERT INTO "catalogue_categorieevaluation" VALUES(23,'Contrôle Continu',50,11);
INSERT INTO "catalogue_categorieevaluation" VALUES(24,'TP',50,11);
INSERT INTO "catalogue_categorieevaluation" VALUES(25,'Projet',70,12);
INSERT INTO "catalogue_categorieevaluation" VALUES(26,'Contrôle Continu',30,12);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'accounts','profile');
INSERT INTO "django_content_type" VALUES(8,'catalogue','cataloguemodule');
INSERT INTO "django_content_type" VALUES(9,'catalogue','categorieevaluation');
INSERT INTO "django_content_type" VALUES(10,'inscription','inscription');
INSERT INTO "django_content_type" VALUES(11,'inscription','modulechoisi');
INSERT INTO "django_content_type" VALUES(12,'inscription','note');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-05-21 11:23:12.790762');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-05-21 11:23:12.835500');
INSERT INTO "django_migrations" VALUES(3,'accounts','0001_initial','2026-05-21 11:23:12.850477');
INSERT INTO "django_migrations" VALUES(4,'admin','0001_initial','2026-05-21 11:23:12.866891');
INSERT INTO "django_migrations" VALUES(5,'admin','0002_logentry_remove_auto_add','2026-05-21 11:23:12.881181');
INSERT INTO "django_migrations" VALUES(6,'admin','0003_logentry_add_action_flag_choices','2026-05-21 11:23:12.891865');
INSERT INTO "django_migrations" VALUES(7,'contenttypes','0002_remove_content_type_name','2026-05-21 11:23:12.909939');
INSERT INTO "django_migrations" VALUES(8,'auth','0002_alter_permission_name_max_length','2026-05-21 11:23:12.925340');
INSERT INTO "django_migrations" VALUES(9,'auth','0003_alter_user_email_max_length','2026-05-21 11:23:12.936333');
INSERT INTO "django_migrations" VALUES(10,'auth','0004_alter_user_username_opts','2026-05-21 11:23:12.946326');
INSERT INTO "django_migrations" VALUES(11,'auth','0005_alter_user_last_login_null','2026-05-21 11:23:12.956250');
INSERT INTO "django_migrations" VALUES(12,'auth','0006_require_contenttypes_0002','2026-05-21 11:23:12.960862');
INSERT INTO "django_migrations" VALUES(13,'auth','0007_alter_validators_add_error_messages','2026-05-21 11:23:12.969305');
INSERT INTO "django_migrations" VALUES(14,'auth','0008_alter_user_username_max_length','2026-05-21 11:23:12.980662');
INSERT INTO "django_migrations" VALUES(15,'auth','0009_alter_user_last_name_max_length','2026-05-21 11:23:12.990975');
INSERT INTO "django_migrations" VALUES(16,'auth','0010_alter_group_name_max_length','2026-05-21 11:23:13.003577');
INSERT INTO "django_migrations" VALUES(17,'auth','0011_update_proxy_permissions','2026-05-21 11:23:13.011860');
INSERT INTO "django_migrations" VALUES(18,'auth','0012_alter_user_first_name_max_length','2026-05-21 11:23:13.022639');
INSERT INTO "django_migrations" VALUES(19,'catalogue','0001_initial','2026-05-21 11:23:13.036026');
INSERT INTO "django_migrations" VALUES(20,'inscription','0001_initial','2026-05-21 11:23:13.064634');
INSERT INTO "django_migrations" VALUES(21,'sessions','0001_initial','2026-05-21 11:23:13.075410');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "inscription_inscription" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "annee_academique" varchar(9) NOT NULL, "statut" varchar(12) NOT NULL, "date_creation" datetime NOT NULL, "etudiant_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "inscription_inscription" VALUES(1,'2025-2026','verrouillee','2026-05-21 11:24:02.055532',2);
INSERT INTO "inscription_inscription" VALUES(2,'2025-2026','verrouillee','2026-05-21 11:24:02.217724',3);
INSERT INTO "inscription_inscription" VALUES(3,'2025-2026','ouverte','2026-05-21 11:24:02.284263',4);
CREATE TABLE "inscription_modulechoisi" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "inscription_id" bigint NOT NULL REFERENCES "inscription_inscription" ("id") DEFERRABLE INITIALLY DEFERRED, "module_catalogue_id" bigint NOT NULL REFERENCES "catalogue_cataloguemodule" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "inscription_modulechoisi" VALUES(1,1,1);
INSERT INTO "inscription_modulechoisi" VALUES(2,1,2);
INSERT INTO "inscription_modulechoisi" VALUES(3,1,3);
INSERT INTO "inscription_modulechoisi" VALUES(4,1,6);
INSERT INTO "inscription_modulechoisi" VALUES(5,1,7);
INSERT INTO "inscription_modulechoisi" VALUES(6,1,10);
INSERT INTO "inscription_modulechoisi" VALUES(7,1,4);
INSERT INTO "inscription_modulechoisi" VALUES(8,1,5);
INSERT INTO "inscription_modulechoisi" VALUES(9,2,1);
INSERT INTO "inscription_modulechoisi" VALUES(10,2,6);
INSERT INTO "inscription_modulechoisi" VALUES(11,2,7);
INSERT INTO "inscription_modulechoisi" VALUES(12,2,8);
INSERT INTO "inscription_modulechoisi" VALUES(13,2,4);
INSERT INTO "inscription_modulechoisi" VALUES(14,2,5);
INSERT INTO "inscription_modulechoisi" VALUES(15,2,11);
INSERT INTO "inscription_modulechoisi" VALUES(16,2,12);
INSERT INTO "inscription_modulechoisi" VALUES(17,2,2);
INSERT INTO "inscription_modulechoisi" VALUES(18,3,1);
INSERT INTO "inscription_modulechoisi" VALUES(19,3,2);
INSERT INTO "inscription_modulechoisi" VALUES(20,3,9);
CREATE TABLE "inscription_note" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "valeur" decimal NOT NULL, "date_saisie" datetime NOT NULL, "categorie_id" bigint NOT NULL REFERENCES "catalogue_categorieevaluation" ("id") DEFERRABLE INITIALLY DEFERRED, "module_choisi_id" bigint NOT NULL REFERENCES "inscription_modulechoisi" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "inscription_note" VALUES(1,14,'2026-04-21 11:24:02.108995',1,1);
INSERT INTO "inscription_note" VALUES(2,12,'2026-04-24 11:24:02.108995',2,1);
INSERT INTO "inscription_note" VALUES(3,16,'2026-04-27 11:24:02.108995',3,1);
INSERT INTO "inscription_note" VALUES(4,15,'2026-04-30 11:24:02.108995',4,2);
INSERT INTO "inscription_note" VALUES(5,13,'2026-05-03 11:24:02.108995',5,2);
INSERT INTO "inscription_note" VALUES(6,17,'2026-05-06 11:24:02.108995',6,3);
INSERT INTO "inscription_note" VALUES(7,16,'2026-05-09 11:24:02.108995',7,3);
INSERT INTO "inscription_note" VALUES(8,14,'2026-05-12 11:24:02.108995',8,3);
INSERT INTO "inscription_note" VALUES(9,18,'2026-05-15 11:24:02.108995',13,4);
INSERT INTO "inscription_note" VALUES(10,15,'2026-05-18 11:24:02.108995',14,4);
INSERT INTO "inscription_note" VALUES(11,19,'2026-05-21 11:24:02.274059',13,10);
INSERT INTO "inscription_note" VALUES(12,17,'2026-05-21 11:24:02.279691',14,10);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "accounts_profile_tuteur_id_b92c1e89" ON "accounts_profile" ("tuteur_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE UNIQUE INDEX "catalogue_categorieevaluation_module_id_nom_1c3eaf03_uniq" ON "catalogue_categorieevaluation" ("module_id", "nom");
CREATE INDEX "catalogue_categorieevaluation_module_id_c35859e5" ON "catalogue_categorieevaluation" ("module_id");
CREATE UNIQUE INDEX "inscription_inscription_etudiant_id_annee_academique_ceadec2c_uniq" ON "inscription_inscription" ("etudiant_id", "annee_academique");
CREATE INDEX "inscription_inscription_etudiant_id_71bfa958" ON "inscription_inscription" ("etudiant_id");
CREATE UNIQUE INDEX "inscription_modulechoisi_inscription_id_module_catalogue_id_a27d97ec_uniq" ON "inscription_modulechoisi" ("inscription_id", "module_catalogue_id");
CREATE INDEX "inscription_modulechoisi_inscription_id_a645503c" ON "inscription_modulechoisi" ("inscription_id");
CREATE INDEX "inscription_modulechoisi_module_catalogue_id_374fb634" ON "inscription_modulechoisi" ("module_catalogue_id");
CREATE UNIQUE INDEX "inscription_note_module_choisi_id_categorie_id_aff1a90a_uniq" ON "inscription_note" ("module_choisi_id", "categorie_id");
CREATE INDEX "inscription_note_categorie_id_8dd936b3" ON "inscription_note" ("categorie_id");
CREATE INDEX "inscription_note_module_choisi_id_0e27bec8" ON "inscription_note" ("module_choisi_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',21);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',0);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',12);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',48);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('auth_user',5);
INSERT INTO "sqlite_sequence" VALUES('catalogue_cataloguemodule',12);
INSERT INTO "sqlite_sequence" VALUES('catalogue_categorieevaluation',26);
INSERT INTO "sqlite_sequence" VALUES('accounts_profile',4);
INSERT INTO "sqlite_sequence" VALUES('inscription_inscription',3);
INSERT INTO "sqlite_sequence" VALUES('inscription_modulechoisi',20);
INSERT INTO "sqlite_sequence" VALUES('inscription_note',12);
COMMIT;
