# Generated by Django 6.0.5 on 2026-05-21 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(default='2025-2026', max_length=9)),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('verrouillee', 'Verrouillée')], default='ouverte', max_length=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscription',
                'unique_together': {('etudiant', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='ModuleChoisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_choisis', to='inscription.inscription')),
                ('module_catalogue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules_choisis', to='catalogue.cataloguemodule')),
            ],
            options={
                'verbose_name': 'Module choisi',
                'unique_together': {('inscription', 'module_catalogue')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='catalogue.categorieevaluation')),
                ('module_choisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscription.modulechoisi')),
            ],
            options={
                'verbose_name': 'Note',
                'ordering': ['date_saisie'],
                'unique_together': {('module_choisi', 'categorie')},
            },
        ),
    ]
