# Generated by Django 6.0.5 on 2026-05-21 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('tuteur', 'Tuteur')], default='etudiant', max_length=10)),
                ('tuteur', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'tuteur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parraines', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
