# Generated by Django 6.0.5 on 2026-05-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, unique=True, verbose_name='Intitulé')),
                ('coefficient', models.PositiveIntegerField(verbose_name='Coefficient')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Module du catalogue',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='CategorieEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Poids (%)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='catalogue.cataloguemodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': "Catégorie d'évaluation",
                'unique_together': {('module', 'nom')},
            },
        ),
    ]
